# Generated by Django 5.1.4 on 2025-04-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_owner_message_reciver_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciver',
            new_name='receiver',
        ),
    ]
