# Generated by Django 5.1.4 on 2025-04-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_chat_alter_message_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chattwouser',
            old_name='creted',
            new_name='created',
        ),
    ]
