# Generated by Django 5.1.4 on 2025-04-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_photo_alter_message_text_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='saved_message_photos/%Y/%m/%d'),
        ),
    ]
