# Generated by Django 5.1.4 on 2025-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
