# Generated by Django 5.1.4 on 2025-04-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
