# Generated by Django 5.1.4 on 2025-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.ImageField(upload_to='group_avatar/<django.db.models.fields.CharField>/2025/07/04/'),
        ),
    ]
